### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Wafer-Li**
I am sorry for that

### CODE REVIEW

**Comment by magicae** [comment]
建议把上个pr里的openItem改成showItemInFolder 然后加上具体的文件名/文件夹名 这样可以保证打开文件夹的时候同时被选中了

**Comment by Wafer-Li** [comment]
我先鼓捣鼓捣

**Comment by Wafer-Li** [comment]
I have no idea how to select multiple files/folders

**Comment by magicae** [comment]
wont select them if there are multiple

**Pull request merged**
